print("Hey How are You")

#SINGLE LINE COMMENT

'''THIS IS MULTI LINE COMMENT 
    WELCOME TO NSR PYTHON LEARNING JOURNEY
    THNX...
'''

#USING CTRL + FORWARD SLASH
# HEY
# HOW 
# ARE 
# YOU
# ?